name: Lint Code Base

on:
  push:

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      statuses: write # for github/super-linter/slim to mark status of each linter run
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install dependencies
        run: npm install --no-package-lock

      - name: Lint Code Base
        uses: super-linter/super-linter/slim@9e863354e3ff62e0727d37183162c4a88873df41 # v8.6.0
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IGNORE_GITIGNORED_FILES: true
          LOG_LEVEL: NOTICE
          SUPPRESS_POSSUM: true
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_BIOME_FORMAT: false
          VALIDATE_BIOME_LINT: false
          VALIDATE_CHECKOV: false
          VALIDATE_HTML_PRETTIER: false
          VALIDATE_JSCPD: false
          VALIDATE_MARKDOWN: false
