---
name: Lint Code Base

on:
  push:

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      statuses: write # for github/super-linter/slim to mark status of each linter run
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install dependencies
        run: npm install --no-package-lock

      - name: Lint Code Base
        uses: super-linter/super-linter/slim@4ce20838b8ab83717e78138c5b3a1407148e0918 # v8.7.0
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IGNORE_GITIGNORED_FILES: true
          LOG_LEVEL: NOTICE
          SUPPRESS_POSSUM: true
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_BIOME_FORMAT: false
          VALIDATE_BIOME_LINT: false
          VALIDATE_CHECKOV: false
          VALIDATE_HTML_PRETTIER: false
          VALIDATE_JSCPD: false
          VALIDATE_MARKDOWN: false
          VALIDATE_NATURAL_LANGUAGE: false
